### PR TITLE
fixed composer.json with broken datatable asset dependency

### PR DESCRIPTION
**Pull request by yygycqipm**

### CODE REVIEW

**Comment by ZAYEC77** [comment]
Hello, thanks for PR.
Can you check [this one](https://github.com/NullRefExcep/yii2-datatables/pull/32) and [this issue](https://github.com/NullRefExcep/yii2-datatables/issues/31)?

**Comment by AthmaneKhl** [comment]
Hi, the assets  in "class DataTableAsset"  link to "datatables-plugins" , but the real bower assets are in  "datatables.**net**-plugins". 

I could make it work with the [custom assets manager](https://github.com/NullRefExcep/yii2-datatables#custom-assets) , but the default should work out of the box.

**Comment by ZAYEC77** [comment]
@DrokTor did you check links from my previous comment?

**Comment by AthmaneKhl** [comment]
@ZAYEC77 , yes I did before posting, if I'm not mistaken an issue was corrected 21 days ago.

I just installed the extension around 5 days ago. so it should contain the corrected version ?

**Comment by ZAYEC77** [comment]
@DrokTor, seems like this PR is actual. Thanks.

**Comment by AthmaneKhl** [comment]
@ZAYEC77  Thanks for your effort.

**Pull request merged**
