### PR TITLE
DataTableAction query parameter can be Closure.

### PR DESCRIPTION
**Pull request by alxlnk**

### CODE REVIEW

**Review by ZAYEC77 — APPROVED** [review]

**Comment by Radon8472** [comment]
Basicly the code looks good,
Maybe you could add this in version 1.1.3 because I already created a release for 1.1.2?

Ah, and please update README with an usage example for the closure parameter.

**Review by Radon8472 — APPROVED** [review]

**Comment by Radon8472** [comment]
@alxlnk The pr is approved, you can merge now, when you are ready

**Comment by alxlnk** [comment]
@Radon8472 I can't merge because I don't have write access. You should do this.

**Comment by ZAYEC77** [comment]
@alxlnk merged 👌

**Comment by alxlnk** [comment]
@ZAYEC77 And don't forget about release new version 😉

**Comment by ZAYEC77** [comment]
@Radon8472 please add new release when you will be able

**Pull request merged**
